name: planesign_mobile
description: A mobile app for interacting with a RaspberryPi

publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: ^3.4.0
  flutter: 3.32.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0
  flutter_blue_plus: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true