name: planesign_mobile
description: A mobile app for interacting with a RaspberryPi

publish_to: 'none'

version: 0.2.0+2026022401

environment:
  sdk: ^3.4.0
  flutter: 3.32.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0
  flutter_blue_plus: ^2.1.1
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: "launcher_icon"
  min_sdk_android: 32
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"